Update Индивидуалальное задание

diff --git a/Индивидуалальное задание b/Индивидуалальное задание
--- a/Индивидуалальное задание
+++ b/Индивидуалальное задание
@@ -1,1 +1,77 @@
+#!/bin/bash
+#5	Написать скрипт, находящий в заданном каталоге и всех его подкаталогах все файлы, владельцем которых является заданный пользователь.
+#Имя владельца и каталог задаются пользователем в качестве первого и второго аргумента командной строки. 
+#Скрипт выводит результаты в файл (третий аргумент командной строки) в виде полный путь, имя файла, его размер.  
+#На консоль выводится общее число просмотренных файлов
+
+set -eu
+
+if [[ "$#" -ne 3 ]]; then
+
+  echo "Invalid number of arguments"
+
+  exit 1
+
+fi
+
+
+target_owner=${1}
+
+src_dir=${2}
+
+output_file=${3}
+
+
+if ! id "${target_owner}" &> /dev/null; then
+
+  echo "User '${target_owner}' not found"
+
+  exit 1
+
+fi
+
+
+if [[ ! -d ${src_dir} ]]; then
+
+  echo "Source folder '${src_dir}' does not exist"
+
+  exit 1
+
+fi
+
+
+if [[ -f "${output_file}" ]]; then
+
+  echo "Output file '${output_file}' already exists"
+
+  exit 1
+
+fi
+
+
+total_files=0
+
+find ${src_dir} -type f -print | {
+
+
+  while read -r f; do
+
+    file=$(realpath ${f})
+
+    total_files=$((total_files + 1))
+
+    file_owner=$(stat --format='%U' ${file})
+
+    if [[ "${file_owner}" == "${target_owner}" ]]; then
+
+      echo $(dirname ${file}) $(basename ${file}) $(stat --format='%s' ${file}) >> ${output_file}
+
+    fi
+
+  done
+
+
+  echo "Total number of processed files: ${total_files}"
+
+}
 
